name: rd_user_cd
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  qr_flutter: ^4.1.0
  
flutter:

  uses-material-design: true